In [5]:
import torch 

In [6]:
a=3
b=1
c=a/b
c

3.0

In [8]:
a=3
b=1
c=torch.div(a, b)
c

tensor(3.)

In [14]:
a = torch.tensor(3)
b= torch.tensor(1)
a.div(b)

tensor(3.)

In [17]:
a = torch.tensor(3.0)  # 注意添加小数点
b = torch.tensor(1.5)

a.div_(b)  # 成功执行

tensor(2.)

In [18]:
a.div(b)

tensor(1.3333)

In [20]:
a=torch.ones(2,3,4,5)
a

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])

In [ ]:
tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

tensor([[[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]],


        [[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],

         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]])

In [21]:
b=torch.ones(2,3,5,4)
b

tensor([[[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]],


        [[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],

         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]])

In [24]:
a.matmul(b)

tensor([[[[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.]],

         [[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.]],

         [[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.]]],


        [[[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.]],

         [[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.]],

         [[5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.],
          [5., 5., 5., 5.]]]])

In [40]:
a=torch.rand(2,3)
b=torch.rand(1,3)

In [41]:
torch.eq(a, b)

tensor([[False, False, False],
        [False, False, False]])

In [42]:
torch.equal(a, b)

False

In [ ]:
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
torch.max(a, dim=1)  

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))